spring:
  application:
    name: ems-service-discovery
server:
  port: ${SERVER.PORT:4340}
eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.ADDRESS:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA.INSTANCE.HTTP-PROTOCOL:http}://${eureka.instance.hostname}:${server.port}/eureka/ 